"""откат, колонка убрана

Revision ID: 37fa0a012a8b
Revises: 59ef7bf32e06
Create Date: 2024-10-17 20:29:58.758172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fa0a012a8b'
down_revision: Union[str, None] = '59ef7bf32e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'advice_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('advice_enabled', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
