"""Добавлена колонка advice_enabled

Revision ID: 59ef7bf32e06
Revises: 3128b835c2a2
Create Date: 2024-10-17 20:26:54.581031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ef7bf32e06'
down_revision: Union[str, None] = '3128b835c2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Enum('ВЫСОКИЙ', 'НИЗКИЙ', name='priority'), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('advice_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'advice_enabled')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
